import { useState, useRef } from "react";
import * as React from "react";
import { Header } from "@/components/header";
import { TruckVisualizer } from "@/components/truck-visualizer";
import { optimizeFleet } from "@/lib/optimizer";
import { parseExcel } from "@/lib/excel-parser";

import { Truck, Order, OptimizationResult } from "@/lib/types";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Station } from "@shared/schema";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Checkbox } from "@/components/ui/checkbox";
import { cn } from "@/lib/utils";
import {
  BarChart,
  Activity,
  Truck as TruckIcon,
  Package,
  Upload,
  ChevronLeft,
  ChevronRight,
  CheckCircle,
  RotateCw,
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { motion, AnimatePresence } from "framer-motion";

export default function Dashboard() {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const fileInputRef = useRef<HTMLInputElement>(null);

  // --- 1. Data Fetching ---
  const { data: trucks = [] } = useQuery<Truck[]>({
    queryKey: ["/api/trucks"],
    select: (data: any[]) => {
      // Transform DB trucks to App Truck type
      return data.map(t => ({
        id: t.id,
        name: t.driverName || t.licensePlate, // Fallback
        licensePlate: t.licensePlate,
        maxWeight: t.capacity.reduce((a: number, b: number) => a + b, 0), // Calculate total
        status: t.status === 'AVAILABLE' ? 'IDLE' : t.status, // Map status
        assignedZone: null,
        compartments: t.capacity.map((cap: number, idx: number) => ({
          id: `comp-${t.id}-${idx}`,
          capacity: cap,
          currentLoad: 0,
          productId: null,
          orderIds: []
        }))
      }));
    }
  });

  const { data: stations = [] } = useQuery<Station[]>({
    queryKey: ["/api/stations"],
  });

  const { data: dbOrders = [], isLoading: isLoadingOrders } = useQuery<any[]>({
    queryKey: ["/api/orders"],
  });

  // Transform DB orders to App Order type
  const orders = React.useMemo(() => {
    return dbOrders.map(o => ({
      ...o,
      status: o.status as any,
    })) as Order[];
  }, [dbOrders]);

  // --- 2. Local State ---
  const [selectedOrderIds, setSelectedOrderIds] = useState<Set<string>>(new Set());

  // Optimization State
  const [simulationResult, setSimulationResult] = useState<OptimizationResult | null>(null);
  const [stats, setStats] = useState({ fillRate: 0, volumeMoved: 0 });

  // --- 3. Pagination State ---
  const ITEMS_PER_PAGE = 10;
  const [ordersPage, setOrdersPage] = useState(1);
  const [trucksPage, setTrucksPage] = useState(1);

  // --- 3. Handlers ---

  const handleFileUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      try {
        const parsedOrders = await parseExcel(file, stations);
        if (parsedOrders.length === 0) {
          toast({ title: "Attention", description: "Aucune commande compatible trouvée dans le fichier.", variant: "destructive" });
        } else {
          // 1. Prepare for DB (remove temp IDs if they are generated by parser)
          const dbPayload = parsedOrders.map(({ id, ...rest }) => rest);

          // 2. Save to Server
          const res = await fetch("/api/orders/batch", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(dbPayload),
          });

          if (!res.ok) throw new Error(await res.text());

          // 3. Refresh all related data
          queryClient.invalidateQueries({ queryKey: ["/api/orders"] });
          queryClient.invalidateQueries({ queryKey: ["/api/orders/all"] });
          toast({ title: "Succès", description: `${parsedOrders.length} commandes importées et sauvegardées.` });
        }
      } catch (e) {
        toast({ title: "Erreur", description: "Erreur lors de l'importation ou de la sauvegarde.", variant: "destructive" });
        console.error(e);
      }
    }
  };

  const handleOptimize = () => {
    // Filter orders
    const ordersToOptimize = orders.filter(o => selectedOrderIds.has(o.id));
    if (ordersToOptimize.length === 0) {
      toast({ title: "Erreur", description: "Veuillez sélectionner au moins une commande.", variant: "destructive" });
      return;
    }

    // Run Algorithm
    const result = optimizeFleet(trucks, ordersToOptimize);

    // Update State
    setSimulationResult(result);
    setStats({
      fillRate: Math.round(result.fillRate),
      volumeMoved: result.totalVolumeMoved
    });

    toast({
      title: "Optimisation Terminée",
      description: `Taux de remplissage : ${result.fillRate.toFixed(1)}% | Volume : ${result.totalVolumeMoved}L`,
    });
  };

  const handleValidateTruck = async (truck: Truck) => {
    try {
      const planData = {
        truckId: truck.id,
        licensePlate: truck.licensePlate,
        totalVolume: truck.compartments.reduce((sum, c) => sum + c.currentLoad, 0),
        fillRate: Math.round((truck.compartments.reduce((sum, c) => sum + c.currentLoad, 0) / (truck.maxWeight || 1)) * 100),
        zone: truck.assignedZone || 'Inconnue',
        plan: truck.compartments.map(c => ({
          capacity: c.capacity,
          load: c.currentLoad,
          product: c.productId,
          orders: c.orderIds
        }))
      };

      const res = await fetch("/api/simulation/validate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(planData),
      });

      if (!res.ok) throw new Error(await res.text());

      toast({
        title: "Camion Validé",
        description: `Le camion ${truck.licensePlate} est désormais en transit.`,
      });

      // 1. Refresh database data (this will remove loaded orders and update truck status)
      queryClient.invalidateQueries({ queryKey: ["/api/orders"] });
      queryClient.invalidateQueries({ queryKey: ["/api/trucks"] });
      queryClient.invalidateQueries({ queryKey: ["/api/validations"] });

      // 2. We can clear the simulation result if needed, or keep it to show remaining
      // For now, let's keep it but mark the truck as IN_TRANSIT locally for immediate UI feedback
      if (simulationResult) {
        setSimulationResult({
          ...simulationResult,
          trucks: simulationResult.trucks.map(t =>
            t.id === truck.id ? { ...t, status: 'IN_TRANSIT' } : t
          )
        });
      }

    } catch (e) {
      toast({ title: "Erreur", description: "Échec de la validation du camion.", variant: "destructive" });
      console.error(e);
    }
  };

  const toggleOrder = (id: string) => {
    const next = new Set(selectedOrderIds);
    if (next.has(id)) next.delete(id);
    else next.add(id);
    setSelectedOrderIds(next);
  };

  // Derived state for display
  const displayTrucks = simulationResult ? simulationResult.trucks : trucks;
  const availableCount = displayTrucks.filter(t => t.status === 'IDLE').length;
  const activeCount = displayTrucks.filter(t => t.status !== 'IDLE').length;
  const totalFleet = trucks.length;

  // Reset pages when data changes
  React.useEffect(() => { setOrdersPage(1); }, [orders]);
  React.useEffect(() => { setTrucksPage(1); }, [displayTrucks]);

  // Pagination Logic
  const paginatedOrders = orders.slice((ordersPage - 1) * ITEMS_PER_PAGE, ordersPage * ITEMS_PER_PAGE);
  const totalOrdersPages = Math.max(1, Math.ceil(orders.length / ITEMS_PER_PAGE));

  const paginatedTrucks = displayTrucks.slice((trucksPage - 1) * ITEMS_PER_PAGE, trucksPage * ITEMS_PER_PAGE);
  const totalTrucksPages = Math.max(1, Math.ceil(displayTrucks.length / ITEMS_PER_PAGE));

  return (
    <div className="min-h-screen bg-background text-foreground p-6 font-sans bg-grid-pattern">
      <Header>
        <input
          type="file"
          ref={fileInputRef}
          className="hidden"
          accept=".xlsx, .xls"
          onChange={handleFileUpload}
        />
        <Button variant="outline" className="border-primary/20 hover:bg-primary/10 text-primary" onClick={() => window.location.reload()}>
          <RotateCw className="mr-2 h-4 w-4" /> Actualiser
        </Button>
        <Button variant="outline" className="border-primary/20 hover:bg-primary/10 text-primary" onClick={() => fileInputRef.current?.click()}>
          <Upload className="mr-2 h-4 w-4" /> Importer Excel
        </Button>
        <Button onClick={handleOptimize} className="bg-primary hover:bg-primary/90 text-primary-foreground font-bold shadow-[0_0_15px_rgba(251,146,60,0.3)]">
          <Activity className="mr-2 h-4 w-4" /> Lancer l'Optimiseur
        </Button>
      </Header>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 flex flex-col gap-6">
          {/* Top Stats Row */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <Card className="bg-card/50 border-primary/20">
              <CardContent className="pt-6">
                <div className="flex items-center justify-between">
                  <div className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Taux de Remplissage</div>
                  <BarChart className="h-4 w-4 text-primary" />
                </div>
                <div className="mt-2 text-3xl font-bold font-mono text-primary">{stats.fillRate}%</div>
              </CardContent>
            </Card>
            <Card className="bg-card/50 border-primary/20">
              <CardContent className="pt-6">
                <div className="flex items-center justify-between">
                  <div className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Volume Déplacé</div>
                  <Package className="h-4 w-4 text-emerald-500" />
                </div>
                <div className="mt-2 text-3xl font-bold font-mono text-emerald-500">
                  {stats.volumeMoved.toLocaleString()} <span className="text-sm font-light">L</span>
                </div>
              </CardContent>
            </Card>
            <Card className="bg-card/50 border-primary/20 relative group">
              <CardContent className="pt-6">
                <div className="flex items-center justify-between">
                  <div className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Camions Actifs</div>
                  <div className="flex items-center gap-2 mt-1">
                    <TruckIcon className="h-4 w-4 text-blue-500" />
                  </div>
                </div>
                <div className="mt-2 text-3xl font-bold font-mono text-blue-500">
                  {activeCount} <span className="text-sm font-light">/ {totalFleet}</span>
                </div>
              </CardContent>
            </Card>
            <Card className="bg-card/50 border-primary/20 relative group">
              <CardContent className="pt-6">
                <div className="flex items-center justify-between">
                  <div className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Camions Disponibles</div>
                  <div className="flex items-center gap-2 mt-1">
                    <CheckCircle className="h-4 w-4 text-emerald-500" />
                  </div>
                </div>
                <div className="mt-2 text-3xl font-bold font-mono text-emerald-500">
                  {availableCount} <span className="text-sm font-light">/ {totalFleet}</span>
                </div>
              </CardContent>
            </Card>
          </div>

          <Card className="flex-1 border-border bg-card/30 flex flex-col">
            <CardHeader>
              <div className="flex items-center justify-between">
                <CardTitle className="flex items-center gap-2 text-sm uppercase tracking-widest font-mono">
                  <TruckIcon className="h-5 w-5 text-primary" /> Statut de la Flotte
                </CardTitle>
                <div className="flex items-center gap-2">
                  <Button
                    variant="outline" size="icon" className="h-7 w-7"
                    onClick={() => setTrucksPage(p => Math.max(1, p - 1))}
                    disabled={trucksPage === 1}
                  >
                    <ChevronLeft className="h-4 w-4" />
                  </Button>
                  <span className="text-[10px] font-mono">{trucksPage} / {totalTrucksPages}</span>
                  <Button
                    variant="outline" size="icon" className="h-7 w-7"
                    onClick={() => setTrucksPage(p => Math.min(totalTrucksPages, p + 1))}
                    disabled={trucksPage === totalTrucksPages}
                  >
                    <ChevronRight className="h-4 w-4" />
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent className="space-y-4 flex-1 overflow-auto pr-2">
              {paginatedTrucks.map(truck => (
                <TruckVisualizer
                  key={truck.id}
                  truck={truck}
                  allOrders={orders}
                  onValidate={handleValidateTruck}
                />
              ))}
            </CardContent>
          </Card>
        </div>

        <div className="space-y-6">
          <Card className="h-full border-border bg-card/30 flex flex-col min-h-[500px]">
            <CardHeader>
              <div className="flex items-center justify-between">
                <CardTitle className="flex items-center gap-2 text-sm uppercase tracking-widest font-mono">
                  <Package className="h-5 w-5 text-primary" /> Commandes Régler
                </CardTitle>
                <div className="flex items-center gap-2">
                  <Button
                    variant="outline" size="icon" className="h-7 w-7"
                    onClick={() => setOrdersPage(p => Math.max(1, p - 1))}
                    disabled={ordersPage === 1}
                  >
                    <ChevronLeft className="h-4 w-4" />
                  </Button>
                  <span className="text-[10px] font-mono">{ordersPage} / {totalOrdersPages}</span>
                  <Button
                    variant="outline" size="icon" className="h-7 w-7"
                    onClick={() => setOrdersPage(p => Math.min(totalOrdersPages, p + 1))}
                    disabled={ordersPage === totalOrdersPages}
                  >
                    <ChevronRight className="h-4 w-4" />
                  </Button>
                </div>
              </div>
              <div className="flex items-center gap-2 mt-2">
                <Button variant="ghost" className="text-[10px] h-6 p-0 hover:bg-transparent" onClick={() => setSelectedOrderIds(new Set(orders.map(o => o.id)))}>Tout Sélectionner</Button>
                <Separator orientation="vertical" className="h-3" />
                <Button variant="ghost" className="text-[10px] h-6 p-0 hover:bg-transparent" onClick={() => setSelectedOrderIds(new Set())}>Désélectionner</Button>
              </div>
            </CardHeader>
            <CardContent className="flex-1 overflow-auto pr-2">
              {/* Orders List */}
              {orders.length === 0 ? (
                <div className="flex flex-col items-center justify-center h-40 text-muted-foreground text-sm opacity-50">
                  <Upload className="h-8 w-8 mb-2" />
                  <p>Importez un fichier Excel pour voir les commandes</p>
                </div>
              ) : (
                <div className="space-y-2">
                  <AnimatePresence>
                    {paginatedOrders.map(order => (
                      <motion.div
                        layout
                        initial={{ opacity: 0, x: 20 }}
                        animate={{ opacity: 1, x: 0 }}
                        exit={{ opacity: 0, scale: 0.9 }}
                        key={order.id}
                        className={cn(
                          "p-3 bg-card border rounded-sm transition-all flex items-start gap-3",
                          selectedOrderIds.has(order.id) ? "border-primary/50 bg-primary/5" : "border-border opacity-60"
                        )}
                      >
                        <Checkbox
                          id={order.id}
                          checked={selectedOrderIds.has(order.id)}
                          onCheckedChange={() => toggleOrder(order.id)}
                          className="mt-1"
                        />
                        <div className="flex-1 grid grid-cols-1 gap-2 text-sm">
                          <div className="flex justify-between items-center">
                            <span className="font-mono text-primary font-bold">{order.orderNumber}</span>
                            <span className="font-mono font-bold text-xs">{order.quantity.toLocaleString()} L</span>
                          </div>
                          <div className="text-muted-foreground text-xs truncate">{order.client}</div>
                          <div className="flex justify-between items-end">
                            <div className="flex flex-col">
                              <span className="truncate text-xs">{order.station}</span>
                              <span className="text-[9px] uppercase font-bold text-blue-400">{order.zone}</span>
                            </div>
                            <span className={cn(
                              "text-[9px] px-1 rounded border",
                              order.product.includes("DIESEL") ? "border-yellow-500/50 text-yellow-500" :
                                order.product.includes("SP95") ? "border-green-500/50 text-green-500" : "border-gray-500 text-gray-400"
                            )}>{order.product}</span>
                          </div>
                        </div>
                      </motion.div>
                    ))}
                  </AnimatePresence>
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
